[programs.localnet]
counter_manager = "J15Nxu5dcMEyeQFymh1qvk3XzSLZcLyr9mCmCc8PSEhJ"
tracker = "FkrQyn9eLfWt4VBPHTbufJcydZBdSAUUJRBzVfEaF9GV"
splitdacheck = "9EFLnZiD7Hrb41KsMNW6JTAGFpyZtHb2zAHFUhPQztPi"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts --parallel"
